import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: import.meta.dirname })

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next on every build; the config files are single
    // anonymous exports by convention.
    ignores: [
      '.next/**', 'node_modules/**', 'coverage/**', 'playwright-report/**', 'test-results/**',
      'next-env.d.ts', '*.config.mjs', '*.config.ts',
    ],
  },
  {
    rules: {
      // Money is Decimal everywhere; an unused variable is usually a half-finished edit.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    files: ['src/lib/{money,tax,accounting,payroll,inventory}/**/*.ts', 'src/lib/money.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          // decimal.js returns true for zero here, which silently turns "is this a gain?" into
          // "is this not a loss?". Every sign test in the domain uses greaterThan(0).
          selector: "CallExpression[callee.property.name='isPositive']",
          message: 'decimal.js isPositive() is true for zero. Use greaterThan(0).',
        },
        {
          selector: "CallExpression[callee.object.name='Math'][callee.property.name='round']",
          message: 'Money never goes through Math.round. Use toHalala or toStorage from lib/money.',
        },
      ],
    },
  },
  {
    files: ['src/lib/**/*.ts'],
    rules: {
      // The domain core does no I/O, which is what makes it testable without a database.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: '@prisma/client', message: 'The domain core must not import Prisma.' },
            { name: 'next/navigation', message: 'The domain core must not import from Next.' },
          ],
        },
      ],
    },
  },
]
